apiVersion: apps/v1
kind: Deployment
metadata:
  name: NFS-client-Pod
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      env: NFS-Client-dynamic-prov
  template:
    metadata:
      labels:
        env: NFS-Client-dynamic-prov
    spec:
      serviceAccountName: NFS-dyn-prov-SA
      containers:
        - name: nfs-client-provisioner-container
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: NFS-vol
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: ank/NFS_Dynamic_SC
            - name: NFS_SERVER
              value: 192.168.99.102
            - name: NFS_PATH
              value: /storage
      volumes:
       - name: NFS-vol
         nfs:
           server: 192.168.99.102
           path: /storage
