kind: ServiceAccount
apiVersion: v1
metadata:
  name: NFS-dyn-prov-SA
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: NFS-dyn-prov-CR
rules:
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]    
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: NFS-dyn-prov-CRB
subjects:
  - kind: ServiceAccount
    name: NFS-dyn-prov-SA
    namespace: default
roleRef:
  kind: ClusterRole
  name: NFS-dyn-prov-CR
  apiGroup: rbac.authorization.k8s.io
